#!/bin/sh

if [ $# -ne 2 ]; then
  echo "USAGE: add-usr username password"
  exit 1
fi
mkdir -p /var/lib/registry/auth 2>&1 > /dev/null

AUTHFILE=/var/lib/registry/auth/htpasswd
if [ -f $AUTHFILE ]; then
  userline=$(grep "$1:" $AUTHFILE)
  if [ -n "$userline" ]; then
    echo "[ERROR] user [$1] alredy exists"
    exit 1
  fi
fi

htpasswd -Bbn "$1" "$2" | head -1 >> $AUTHFILE
